#!/bin/bash
lin="LIN_DRIVE"
esp="ESP_DRIVE"
swap="SWAP_DRIVE"
FS="btrfs -f"   # btrfs -f OR ext4

if [ $EUID != 0 ]; then
    sudo "$0" "$@"
    exit $?
fi

umount /mnt
umount LABEL=$esp LABEL=$lin
umount /dev/sdc1 /dev/sdc3
umount /mnt
mkfs.fat -F 32 -n $esp /dev/sdc1
mkfs.$FS -L $lin /dev/sdc3
mkswap -L $swap /dev/sdc2
mount LABEL=$lin /mnt
mount -m LABEL=$esp /mnt/boot

mkdir -p /mnt/home/jason/.packages
mkdir /mnt/shared
mkdir -p /mnt/home/jason/jasorepo

rsync -axHAWXSR --info=progress2 /etc/pacman.d/ /mnt/
rsync -axHAWXSR --info=progress2 /etc/pacman.conf /mnt/

archinstall --advanced --config /home/jason/jasolinux/Configs/user_configuration.json --creds /home/jason/jasolinux/Configs/user_credentials.json --silent
rsync -axHAWXSR --info=progress2 /etc/pacman.conf /mnt/
rsync -axHAWXSR --info=progress2 /etc/pacman.d/ /mnt/
rsync -axHAWXSR --info=progress2 /usr/bin/makepkg /mnt/
rsync -axHAWXSR --info=progress2 /home/jason/.s3cfg /mnt/
rsync -axHAWXSR --info=progress2 /home/jason/.aws
echo "jason ALL=(ALL:ALL) NOPASSWD: ALL" >> /mnt/etc/sudoers
rm -rf /mnt/var/lib/pacman/sync/*
rm -rf /mnt/home/jason/jasorepo/jasorepo.*
rm -rf /mnt/home/jason/jasorepo/*.sig
chown -R jason /mnt/home/jason
chmod -R 777 /mnt/home/jason/jasorepo
arch-chroot -u jason /mnt bash -c "git clone https://github.com/coolduderules/jasolinux.git /home/jason/jasolinux"


#sed -i '$ d' /mnt/etc/sudoers

umount LABEL=$esp LABEL=$lin
umount /dev/sdc1 /dev/sdc3
exit
