#!/bin/bash
lin="LINMAC"
esp="ESPMAC"
#swap="SWAPMAC"
FS="ext4" # btrfs -f OR ext4

if [ $EUID != 0 ]; then
    sudo "$0" "$@"
    exit $?
fi

umount /mnt
umount LABEL=$esp LABEL=$lin
umount /dev/disk/by-label/$esp /dev/disk/by-label/$lin
umount /mnt
mkfs.fat -F 32 -n $esp /dev/disk/by-label/$esp
mkfs.$FS -L $lin /dev/disk/by-label/$lin
#mkswap -L $swap /dev/disk/by-label/$swap
mount /dev/disk/by-label/$lin /mnt
rm -rf /mnt
mount -m /dev/disk/by-label/$esp /mnt/boot
rm -rf /mnt/boot

mkdir -p /mnt/etc/pacman.d/hooks

rsync -axHAWXS --info=progress2 /home/jason/jasolinux/files/etc/pacman.d/ /mnt/etc/pacman.d/
rsync -axHAWXS --info=progress2 /home/jason/jasolinux/files/etc/pacman.conf /mnt/etc/
ln -sf ../run/systemd/resolve/stub-resolv.conf /mnt/etc/resolv.conf
archinstall --advanced --config /home/jason/jasolinux/Source/user_configuration.json --creds /home/jason/jasolinux/Source/user_credentials.json --silent

echo 'Defaults:jason      !authenticate' >>/mnt/etc/sudoers
sed -i 's/#auth           sufficient      pam_wheel.so trust use_uid/auth           sufficient      pam_wheel.so trust use_uid/' /mnt/etc/pam.d/su
find /home/jason/jasolinux/files/ | sed 's/\/home\/jason\/jasolinux\/files//' | xargs -I {} pacrepairfile /mnt{} --uid --gid --mode --root=/mnt --dbpath=/var/lib/pacman
arch-chroot /mnt /home/jason/jasolinux/Scripts/setup.sh
sed -i '$ d' /mnt/etc/sudoers
sed -i 's/auth           sufficient      pam_wheel.so trust use_uid/#auth           sufficient      pam_wheel.so trust use_uid/' /mnt/etc/pam.d/su

#rsync -axHAWXSR --info=progress2 /etc/pacman.conf /mnt/
#rsync -axHAWXSR --info=progress2 /home/jason/.s3cfg /mnt/
#rsync -axHAWXSR --info=progress2 /home/jason/.aws
#rm -rf /mnt/var/lib/pacman/sync/*
#rm -rf /mnt/home/jason/jasorepo/jasorepo
#rm -rf /mnt/home/jason/jasorepo/*.sig
#chown -R jason /mnt/home/jason
#chmod -R 777 /mnt/home/jason/jasorepo
#rsync -axHAWXS --info=progress2 /home/jason/jasolinux/Scripts/jpost.sh /mnt/home/jason/
#arch-chroot -u jason /mnt /home/jason/jpost.sh

umount LABEL=$esp LABEL=$lin
umount /dev/disk/by-label/$esp /dev/disk/by-label/$lin
exit
